version: '3.4'
services:
  api:
    container_name: api
    build: .
    volumes:
      - .:/opt/globo
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_USER=userintegrator
      - DATABASE_PASSWORD=q1w2e3
      - DATABASE_HOST=186.202.159.162
      - DATABASE_PORT=3307
      - DATABASE_NAME=integratordb
      - CONTAINER_QUANTITY=5
      - APPLICATION_SECRETS=Zw4Qe_h9Pg2jhHSHeHjm-CIMbVUp1u1bBrRq2QiPnFw=